version: "2"
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx_rb
    depends_on:
      - web
      - db
    ports:
      - "8089:8089"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
  web:
    image: odoo-xlrd:13.0
    build:
      context: .
      dockerfile: config/dockerfile
    restart: always
    container_name: odoo13
    depends_on:
      - db
    volumes:
      - rb-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:2345:5432"
    volumes:
      - rb-db-data:/var/lib/postgresql/data/pgdata
volumes:
  rb-web-data:
  rb-db-data:
